"""empty message

Revision ID: 59c792f7d902
Revises: 7c9526863d46
Create Date: 2020-07-01 00:16:53.519722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c792f7d902'
down_revision = '7c9526863d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('average_wage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'average_wage')
    # ### end Alembic commands ###
